
exams_dir: "/media/jlsstorage/masstorage/angiograms/Videos" 
clinical_data_excel_path: "/media/masstorage/angiograms/clinical_data.xlsx"
patient_json_path: "/media/masstorage/angiograms/patient_data.json"
exam_json_path: "/media/masstorage/angiograms/exam_data.json"
kf_mask_dir: "/media/masstorage/angiograms/key_masks"

preprocess:
  exams_log: "/media/masstorage/angiograms/preprocessed_exams.log"

training:
  model_name: "VGGRCNNClassifier"
  save_checkpoints: False
  metric: "accuracy" #accuracy or MSE

  data_json: "/home/guests/mas/angiograms/clinical_data.json"
  checkpoints_dir: "/media/masstorage/angiograms/checkpoints"
  performance_dir: "/media/masstorage/angiograms/performance"
  charts_dir: "/home/guests/mas/angiograms/train/charts"

  epochs: 30
  batch_size: 10
  test_size: 0.2
  num_workers: 4
  log_interval: 10 #num of batches

  frame:
    window: 50
    step: 2
    n_mask: 1

  crnn:
    lr: 0.00001
    weight_decay: 0
    cnn:
      in_dim: 224 #default
      # in_dim: 456 #for efficientnet
      # in_dim: 299 #for inceptionv3
      img_x: 256
      img_y: 342
      # fc1_dim:  448
      # fc2_dim: 336
      # out_dim: 224  #latent dim extracted by 2D CNN
      fc1_dim:  1024
      fc2_dim: 768
      out_dim: 512  #latent dim extracted by 2D CNN
      dropout_p: 0.0
    rnn:
      #LSTM
      # hidden_size: 512  #nodes
      # hidden_layers: 3
      # #Linear
      # fc1_dim: 224
      hidden_size: 512  #nodes
      hidden_layers: 3
      #Linear
      fc1_dim: 256
      dropout_p: 0.0

  cnn3d:
    lr: 0.0001
    weight_decay: 0
    img_x: 256
    img_y: 342
    dropout_p: 0.0
    fc1_dim:  256
    fc2_dim: 256

  cnn2d:
    lr: 0.0001
    weight_decay: 0
    img_x: 256
    img_y: 342
    dropout_p: 0.0
    fc1_dim:  256
    fc2_dim: 256

