data_json: "/home/guests/mas/angiograms/clinical_data.json"

training:
  checkpoints_dir: "/home/guests/mas/angiograms/clinical_data.json"
  epochs: 50
  batch_size: 50
  log_interval: 10

  frame:
    window: 25
    step: 2

  crnn:
    cnn:
      fc1_dim:  1024
      fc2_dim: 768
      embed_dim: 224  #encoder output
      dropout_p: 0.0
    rnn:
      #LSTM
      hidden_size:
      hidden_layers:
      #Linear
      fc1_dim: 256
      dropout_p: 0.0

